require('dotenv').config();
const { MongoClient } = require('mongodb');
const names=['Morris Park Bake Shop','Wendy\'s','DJ Reynolds Pub and Restaurant','Riviera Caterer','Toy Kosher Kitchen','Brunos on the Boulevard','Kosher Island','Wilken\'s Fine Food','Regina Caterers','Taste the Tropics Ice Cream','Wild Asia','C & C Catering Service','1 East 66th Street Kitchen','May May Kitchen','Carvel Ice Cream','Nordic Delicacies','Glorious Food','The Movable Feast','Joe\'s Pizza','Katz\'s Delicatessen','Nobu Downtown','Rao\'s','Arthur Avenue Trattoria','Di Fara Pizza','Sushi Yasaka','Café Grumpy','Astoria Coffee','Denino\'s Pizzeria','Enoteca Maria','Takumi Ramen','Hudson Diner'];
const boroughs=['Bronx','Brooklyn','Manhattan','Queens','Staten Island'];
const cuisines=['Bakery','American','Irish','Italian','Jewish/Kosher','Caribbean','Asian','Pizza','Japanese','Café/Coffee/Tea','Diner'];
const streets=['Morris Park Ave','Flatbush Ave','East 57th Street','Queens Boulevard','Hylan Boulevard'];
function records(){return names.map((name,i)=>{const grade=['A','A','A','B','A','B','C'][i%7];const now=new Date();now.setDate(now.getDate()-i*5);const prior=new Date(now);prior.setMonth(prior.getMonth()-6);return{restaurant_id:String(30075445+i),name,borough:boroughs[i%boroughs.length],cuisine:cuisines[i%cuisines.length],address:{building:String(100+i*7),street:streets[i%streets.length],zipcode:String(10001+(i%5)*1000+i)},grades:[{date:now,grade,score:(i*3)%24+2},{date:prior,grade:i%5===0?'B':'A',score:(i*5)%28+3}]}})}
async function seed(){const uri=process.env.MONGODB_URI;if(!uri||uri.includes('YOUR_DB_'))throw new Error('Set MONGODB_URI in .env first.');const client=new MongoClient(uri);try{await client.connect();const c=client.db(process.env.DB_NAME||'dbRestaurants').collection('restaurants');const count=await c.countDocuments();if(count){console.log(`Seed skipped: restaurants already contains ${count} document(s).`);return}const result=await c.insertMany(records());console.log(`Inserted ${result.insertedCount} sample restaurants.`)}finally{await client.close()}}
seed().catch(e=>{console.error(e.message);process.exitCode=1});
